spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          url: jdbc:mysql://sh-cynosdbmysql-grp-hwyktvck.sql.tencentcdb.com:23257/freshmushroom?allowPublicKeyRetrieval=true&useSSL=false
          username: repl
          password: name123321@
          driver-class-name: com.mysql.cj.jdbc.Driver

        slave:
          url: jdbc:mysql://localhost:3306/freshmushroom
          username: root
          password: 12345
          driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        min-idle: 5
        max-pool-size: 20
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  redis:
    host: localhost
    port: 6379

    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

  cache:
    type: redis
    redis:
      time-to-live: 600s
      key-prefix: "cache:"
      cache-null-values: true
      use-key-prefix: true
  mail:
    host: localhost
    port: 1025


  devtools:
    livereload:
      enabled: true

  main:
    allow-bean-definition-overriding: true
server:
  port: 8023